In [1]:
import numpy as np
import pandas as pd
ingredients_all = pd.read_csv('ingredients.csv')


In [2]:
player_count = 3 # declare desired player count

if player_count == 3:
    n_suits = 4
    n_ranks = 6
elif player_count == 4:
    n_suits = 5
    n_ranks = 6
elif player_count == 5:
    n_suits = 5
    n_ranks = 7
elif player_count == 6:
    n_suits = 6
    n_ranks = 7
elif player_count == 7:
    n_suits = 7
    n_ranks = 7

In [3]:
iterations = 20
total_poison = np.empty(iterations).astype(np.int64)
poison_cards = np.empty([iterations, player_count]).astype(np.int64)

for x in range(0, iterations):
    # SETUP
    suits_all = ingredients_all['suit'].unique()
    suits = np.delete(suits_all, np.where(suits_all=='sugar')) # remove sugar
    suits = np.random.choice(suits, size=n_suits, replace=False) # randomly select suits
    ingredients = ingredients_all[ingredients_all['suit'].isin(suits)]
    ingredients = ingredients[ingredients['rank']<=n_ranks] # remove unused ranks

    # DEAL
    deck = ingredients
    players = {} # player hands stored in dictionary
    for i in range(1, player_count+1):
        player_hand = deck.sample(n=7) # randomly select 7 cards
        players['player{0}'.format(i)] = player_hand # assign cards to player
        deck = deck[~deck['name'].isin(player_hand['name'])] # remove those cards from the deck

    # POISON
    poison_card = np.empty(player_count).astype(np.int64)
    i = 0
    for player, hand in players.items():
        lowest_rank = hand['rank'].min()
        poison_card[i] = lowest_rank
        i += 1
    poison = np.sum(poison_card)

    total_poison[x] = poison
    poison_cards[x] = poison_card

print(total_poison)
print(poison_cards)


[3 3 3 4 3 4 5 3 3 4 5 4 3 5 4 3 3 4 3 3]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 2 1]
 [1 1 1]
 [2 1 1]
 [1 1 3]
 [1 1 1]
 [1 1 1]
 [1 2 1]
 [2 2 1]
 [2 1 1]
 [1 1 1]
 [1 2 2]
 [1 2 1]
 [1 1 1]
 [1 1 1]
 [1 1 2]
 [1 1 1]
 [1 1 1]]


C:\Users\Carl\AppData\Local\Temp\ipykernel_10568\4227679132.py:3: RuntimeWarning: invalid value encountered in cast
  poison_cards = np.empty([iterations, player_count]).astype(np.int64)
